//TRANSACTION API
GET http://localhost:5001/transactions/

###

GET http://localhost:5001/transactions/5e4a4ef0fb5fd31eb85fa6ae

###

POST http://localhost:5001/transactions/
Content-Type: application/json

{
  "desc": "Chicken Rice",
  "amount": 2,
  "category": "Food",
  "type": "expense",
  "date": "15 January 2020"
}

###

DELETE http://localhost:5001/transactions/5e48211dcf0ec941d063602a

###

PATCH  http://localhost:5001/transactions/5e48211dcf0ec941d063602a
Content-Type: application/json

{
  "desc": "test",
  "amount": 1200,
  "category": "Food",
  "type": "expense",
  "date": "15 Januari 2020"
}